In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
from scipy.io import wavfile

In [2]:
# load and get the sampling freq & array form audio the input file
sampling_frequency, audio_data = wavfile.read("/home/ix502iv/Documents/Audio_Trad/HMM/custom_commands/demo_fider_ac_0.wav")
sampling_frequency, audio_data

(48000, array([  0,  -1,  -1, ..., -52, -45, -40], dtype=int16))

In [3]:
# normalize the audio values : application of a constant amount of gain to an audio to bring
# amplitude to a target level
audio_data_norm = audio_data / (2.**15)
audio_data == audio_data_norm*(2.**15)

array([ True,  True,  True, ...,  True,  True,  True])

In [4]:
# get the audio length
len_audio = len(audio_data)
len_audio

115096

In [5]:
# apply fourier transform: get the audio from time/space to spatial frequency
transformed_signal = np.fft.fft(audio_data)
half_length = np.ceil((len_audio+1)/2.0)
half_length = int(half_length) # change to int: ceil leaves us at float
half_length

57549

In [7]:
transformed_signal = abs(transformed_signal[0:half_length])
transformed_signal /= float(len_audio)
transformed_signal **- 2

array([4.98497456e+10, 4.45436230e+10, 5.42055445e+10, ...,
       7.12363736e+16, 1.43355480e+16, 3.20462697e+16])

In [9]:
# extract the length of the transformed signal
len_ts = len(transformed_signal)

# sort the even/odd cases
if len_audio % 2:
    transformed_signal[1:len_ts] *= 2
else:
    transformed_signal[1:len_ts-1] *= 2

In [12]:
# extract the powe in db 
power = 10 * np.log10(transformed_signal)
power

array([-53.48831473, -50.23362774, -50.6599186 , ..., -81.25320906,
       -77.77177154, -82.52888741])